var grammarData = {
  "origin": [
    "#name.capitalizeAll#"
  ],
  "name": [
  "#gods#",
  "#animals#",
  "#conditions#",
  "#space_words#",
  "#authors#"
  ],
  "gods": [
    "#roman_deities#",
    "#greek_gods#"
  ],
  "animals": [
    "#cats#",
    "#rabbits#",
    "#common#",
    "#dinosaurs#",
    "#dogs#",
    "#donkeys#",
    "#horses#",
    "#ponies#"
  ],

  "roman_deities": [
    "Apollo",
    "Bacchus",
    "Caelus",
    "Ceres",
    "Cupid",
    "Diana",
    "Fortuna",
    "Janus",
    "Juno",
    "Jupiter",
    "Mars",
    "Mercury",
    "Minerva",
    "Neptune",
    "Nox",
    "Pluto",
    "Proserpina",
    "Saturn",
    "Sol Invicus",
    "Spes",
    "Terra",
    "Venus",
    "Veritas",
    "Vesta",
    "Vulcan"
  ],
  "greek_gods": [
    "Aphrodite",
    "Apollo",
    "Ares",
    "Artemis",
    "Athena",
    "Demeter",
    "Dionysus",
    "Hades",
    "Hephaestus",
    "Hera",
    "Hermes",
    "Hestia",
    "Poseidon",
    "Zeus",
    "Aether",
    "Ananke",
    "Chaos",
    "Chronos",
    "Erebus",
    "Eros",
    "Hypnos",
    "Uranus",
    "Gaia",
    "Phanes",
    "Pontus",
    "Tartarus",
    "Thalassa",
    "Thanatos",
    "Hemera",
    "Nyx",
    "Nemesis"
  ],
  "rabbits":
    [
      "American",
      "American Chinchilla",
      "American Fuzzy Lop",
      "American Sable",
      "Argente Brun",
      "Belgian Hare",
      "Beveren",
      "Blance de Hotot",
      "Britannia Petite",
      "Californian",
      "Champagne D'argent",
      "Checkered Giant",
      "Cinnamon",
      "Creme D'argent",
      "Dutch",
      "Dwarf Hotot",
      "English Angora",
      "English Lop",
      "English Spot",
      "Flemish Giant",
      "Florida White",
      "French Angora",
      "French Lop",
      "Giant Angora",
      "Giant Chinchilla",
      "Harlequin",
      "Havana",
      "Himalayan",
      "Holland Lop",
      "Jersey Wooly",
      "Lilac",
      "Lionhead",
      "Mini Lop",
      "Mini Rex",
      "Mini Satin",
      "Netherland Dwarf",
      "New Zealand",
      "Palomino",
      "Polish",
      "Rex",
      "Rhinelander",
      "Satin",
      "Satin Angora",
      "Silver",
      "Silver Fox",
      "Silver Marten",
      "Standard Chinchilla",
      "Tan",
      "Thrianta"
    ],
   "cats":[
      "Abyssinian",
      "Aegean",
      "American Bobtail",
      "American Curl",
      "American Shorthair",
      "American Wirehair",
      "Arabian Mau",
      "Asian",
      "Asian Semi-longhair",
      "Australian Mist",
      "Balinese",
      "Bambino",
      "Bengal",
      "Birman",
      "Bombay",
      "Brazilian Shorthair",
      "British Longhair",
      "British Semi-longhair",
      "British Shorthair",
      "Burmese",
      "Burmilla",
      "California Spangled",
      "Chantilly-Tiffany",
      "Chartreux",
      "Chausie",
      "Cheetoh",
      "Colorpoint Shorthair",
      "Cornish Rex",
      "Cymric",
      "Cyprus",
      "Devon Rex",
      "Donskoy",
      "Dragon Li",
      "Dwarf cat",
      "Egyptian Mau",
      "European Shorthair",
      "Exotic Shorthair",
      "Foldex",
      "German Rex",
      "Havana Brown",
      "Highlander",
      "Himalayan",
      "Japanese Bobtail",
      "Javanese",
      "Khao Manee",
      "Korat",
      "Korean Bobtail",
      "Korn Ja",
      "Kurilian Bobtail",
      "LaPerm",
      "Lykoi",
      "Maine Coon",
      "Manx",
      "Mekong Bobtail",
      "Minskin",
      "Munchkin",
      "Napoleon",
      "Nebelung",
      "Norwegian Forest cat",
      "Ocicat",
      "Ojos Azules",
      "Oregon Rex",
      "Oriental Bicolor",
      "Oriental Longhair",
      "Oriental Shorthair",
      "PerFold",
      "Persian (Modern)",
      "Persian (Traditional)",
      "Peterbald",
      "Pixie-bob",
      "Raas",
      "Ragamuffin",
      "Ragdoll",
      "Russian Blue",
      "Russian White, Black and Tabby",
      "Sam Sawet",
      "Savannah",
      "Scottish Fold",
      "Selkirk Rex",
      "Serengeti",
      "Serrade Petit",
      "Siamese",
      "Siberian",
      "Singapura",
      "Snowshoe",
      "Sokoke",
      "Somali",
      "Sphynx",
      "Suphalak",
      "Thai",
      "Thai Lilac",
      "Tonkinese",
      "Toyger",
      "Turkish Angora",
      "Turkish Van",
      "Ukrainian Levkoy"
   ],
  "common":
    [
      "aardvark",
      "alligator",
      "alpaca",
      "antelope",
      "ape",
      "armadillo",
      "baboon",
      "badger",
      "bat",
      "bear",
      "beaver",
      "bison",
      "boar",
      "buffalo",
      "bull",
      "camel",
      "canary",
      "capybara",
      "cat",
      "chameleon",
      "cheetah",
      "chimpanzee",
      "chinchilla",
      "chipmunk",
      "cougar",
      "cow",
      "coyote",
      "crocodile",
      "crow",
      "deer",
      "dingo",
      "dog",
      "donkey",
      "dromedary",
      "elephant",
      "elk",
      "ewe",
      "ferret",
      "finch",
      "fish",
      "fox",
      "frog",
      "gazelle",
      "gila monster",
      "giraffe",
      "gnu",
      "goat",
      "gopher",
      "gorilla",
      "grizzly bear",
      "ground hog",
      "guinea pig",
      "hamster",
      "hedgehog",
      "hippopotamus",
      "hog",
      "horse",
      "hyena",
      "ibex",
      "iguana",
      "impala",
      "jackal",
      "jaguar",
      "kangaroo",
      "koala",
      "lamb",
      "lemur",
      "leopard",
      "lion",
      "lizard",
      "llama",
      "lynx",
      "mandrill",
      "marmoset",
      "mink",
      "mole",
      "mongoose",
      "monkey",
      "moose",
      "mountain goat",
      "mouse",
      "mule",
      "muskrat",
      "mustang",
      "mynah bird",
      "newt",
      "ocelot",
      "opossum",
      "orangutan",
      "oryx",
      "otter",
      "ox",
      "panda",
      "panther",
      "parakeet",
      "parrot",
      "pig",
      "platypus",
      "polar bear",
      "porcupine",
      "porpoise",
      "prairie dog",
      "puma",
      "rabbit",
      "raccoon",
      "ram",
      "rat",
      "reindeer",
      "reptile",
      "rhinoceros",
      "salamander",
      "seal",
      "sheep",
      "shrew",
      "silver fox",
      "skunk",
      "sloth",
      "snake",
      "squirrel",
      "tapir",
      "tiger",
      "toad",
      "turtle",
      "walrus",
      "warthog",
      "weasel",
      "whale",
      "wildcat",
      "wolf",
      "wolverine",
      "wombat",
      "woodchuck",
      "yak",
      "zebra"
    ],
  "dinosaurs":
    [
      "Kangnasaurus",
      "Lophostropheus",
      "Spinophorosaurus",
      "Epachthosaurus",
      "Coelurosauria",
      "Lycorhinus",
      "Adasaurus",
      "Draconyx",
      "Ceratops",
      "Lagerpeton",
      "Qiaowanlong",
      "Rhynchosaur",
      "Ningyuansaurus",
      "Palaeolimnornis",
      "Anabisetia",
      "Talarurus",
      "Sphenodontia",
      "Tianyulong",
      "Aepisaurus",
      "Neuquenraptor",
      "Galesaurus",
      "Pachysuchus",
      "Auroraceratops",
      "Hecatasaurus",
      "Barapasaurus",
      "Asiatosaurus",
      "Daanosaurus",
      "Luoyanggia",
      "Eobrontosaurus",
      "Wellnhoferia",
      "Zuolong",
      "Tenchisaurus",
      "Centrosaurus",
      "Falcarius",
      "Ojoraptorsaurus",
      "Lufengocephalus",
      "Vulcanodon",
      "Mollusc",
      "Shunosaurus",
      "Empaterias",
      "Issasaurus",
      "Jiangxisaurus",
      "Laplatasaurus",
      "Aublysodon",
      "Embasaurus",
      "Blikanasaurus",
      "Bonapartenykus",
      "Asiamericana",
      "Arizonasaurus",
      "Cryptoraptor",
      "Morosaurus",
      "Mapusaurus",
      "Buitreraptor",
      "Gravitholus",
      "Vitakrisaurus",
      "Nurosaurus",
      "Cetiosauriscus",
      "Kukufeldia",
      "Propanoplosaurus",
      "Suchoprion",
      "Umarsaurus",
      "Likhoelesaurus",
      "Dasygnathoides",
      "Dubreuillosaurus",
      "Shenzhouraptor",
      "Atrociraptor",
      "Amurosaurus",
      "Latirhinus",
      "Albisaurus",
      "Zupaysaurus",
      "Venenosaurus",
      "Syrmosaurus",
      "Arkharavia",
      "Yueosaurus",
      "Tianchungosaurus",
      "Dyslocosaurus",
      "Sinraptor",
      "Owenodon",
      "Pelycosaur",
      "Duriavenator",
      "Haplocheirus",
      "Epidendrosaurus",
      "Nyasasaurus",
      "Tawasaurus",
      "Lisboasaurus",
      "Ahshislepelta",
      "Magnirostris",
      "Psittacosaurus",
      "Orodromeus",
      "Ostafrikasaurus",
      "Nemegtomaia",
      "Dracorex",
      "Ovoraptor",
      "Amazonsaurus",
      "Leyesaurus",
      "Dollodon",
      "Cryptosaurus",
      "Coahuilaceratops",
      "Variraptor",
      "Panamericansaurus",
      "Nodocephalosaurus",
      "Nasutoceratops",
      "Prosaurolophus",
      "Jingshanosaurus",
      "Teleocrater",
      "Tribelesodon",
      "Mochlodon",
      "Eohadrosaurus",
      "Comanchesaurus",
      "Limnornis",
      "Gigantspinosaurus",
      "Oxalaia",
      "Wuerhosaurus",
      "Mtapaiasaurus",
      "Longisquama",
      "Velocisaurus",
      "Aorun",
      "Sinopliosaurus",
      "Gigantosaurus",
      "Sphenospondylus",
      "Dinotyrannus",
      "Rhabdodon",
      "Kritosaurus",
      "Lamplughsaura",
      "Notohypsilophodon",
      "Tsagantegia",
      "Brontoraptor",
      "Argyrosaurus",
      "Lambeosaurus",
      "Heterosaurus",
      "Tazoudasaurus",
      "Valdoraptor",
      "Microhadrosaurus",
      "Pycnonemosaurus",
      "Manidens",
      "Coelophysis",
      "Hulsanpes",
      "Losillasaurus",
      "Polacanthoides",
      "Lanzhousaurus",
      "Walgettosuchus",
      "Sauroniops",
      "Magulodon",
      "Pneumatoraptor",
      "Altispinax",
      "Alnashetri",
      "Hoplitosaurus",
      "Rahiolisaurus",
      "Luanpingosaurus",
      "Abrosaurus",
      "Palaeosaurus",
      "Iguanoides",
      "Abydosaurus",
      "Riodevasaurus",
      "Stormbergia",
      "Bihariosaurus",
      "Yuanmousaurus",
      "Sphenosuchus",
      "Dashanpusaurus",
      "Crocodilia",
      "Enigmosaurus",
      "Montanoceratops",
      "Frenguellisaurus",
      "Segnosaurus",
      "Kryptops",
      "Labocania",
      "Sinocalliopteryx",
      "Dromiceiomimus",
      "Isisaurus",
      "Archaeornithoides",
      "Deinonychus",
      "Allosaurus",
      "Stephanosaurus",
      "Sinornithoides",
      "Incisivosaurus",
      "Ornitholestes",
      "Ankylosaurus",
      "Plateosaurus",
      "Shidaisaurus",
      "Platyceratops",
      "Agnosphitys",
      "Changdusaurus",
      "Nothosaur",
      "Orthogoniosaurus",
      "Titanoceratops",
      "Dysganus",
      "Lamaceratops",
      "Helioceratops",
      "Nanyangosaurus",
      "Khaan",
      "Cryptodraco",
      "Chasmosaurus",
      "Rileyasuchus",
      "Aeolosaurus",
      "Yizhousaurus",
      "Echinodon",
      "Omnivoropteryx",
      "Lengosaurus",
      "Megadactylus",
      "Mamenchisaurus",
      "Notoceratops",
      "Pachysaurus",
      "Tianzhenosaurus",
      "Zhuchengceratops",
      "Tyreophorus",
      "Nedcolbertia",
      "Shixinggia",
      "Jeholosaurus",
      "Ornithosuchus",
      "Veterupristisaurus",
      "Rayososaurus",
      "Velafrons",
      "Lapparentosaurus",
      "Seismosaurus",
      "Tsuchikurasaurus",
      "Styracosaurus",
      "Dilophosaurus",
      "Gasparinisaura",
      "Xiaotingia",
      "Dromaeosaurus",
      "Scansoriopteryx",
      "Eurolimnornis",
      "Proterosuchid",
      "Nipponosaurus",
      "Brachiosaurus",
      "Vitaridrinda",
      "Mantellodon",
      "Sphaerotholus",
      "Shuosaurus",
      "Koutalisaurus",
      "Cardiodon",
      "Yixianosaurus",
      "Jurassosaurus",
      "Jiutaisaurus",
      "Gryphognathus",
      "Archaeornithomimus",
      "Griphornis",
      "Szechuanosaurus",
      "Pneumatoarthrus",
      "Basutodon",
      "Aletopelta",
      "Tendaguria",
      "Riojasaurus",
      "Creosaurus",
      "Harpymimus",
      "Huaxiagnathus",
      "Carnotaurus",
      "Beipiaosaurus",
      "Teratophoneus",
      "Cedarosaurus",
      "Omosaurus",
      "Wyleyia",
      "Aachenosaurus",
      "Atlantosaurus",
      "Bilbeyhallorum",
      "Balochisaurus",
      "Ouranosaurus",
      "Fukuititan",
      "Sarcolestes",
      "Alocodon",
      "Amphisaurus",
      "Lametasaurus",
      "Raptorex",
      "Sinosaurus",
      "Doratodon",
      "Ankistrodon",
      "Chuanjiesaurus",
      "Parasaurolophus",
      "Albertonykus",
      "Efraasia",
      "Alaskacephale",
      "Torilion",
      "Rapator",
      "Sauroplites",
      "Thecocoelurus",
      "Lirainosaurus",
      "Xixiasaurus",
      "Conchoraptor",
      "Paralititan",
      "Arcusaurus",
      "Becklespinax",
      "Thecodontosaurus",
      "Taveirosaurus",
      "Daemonosaurus",
      "Suuwassea",
      "Albertosaurus",
      "Nouerosaurus",
      "Marshosaurus",
      "Xuanhuasaurus",
      "Algoasaurus",
      "Capitalsaurus",
      "Xenoposeidon",
      "Cryolophosaurus",
      "Gobipteryx",
      "Stereosaurus",
      "Nemegtia",
      "Proyandusaurus",
      "Thyreophora",
      "Xiaosaurus",
      "Tatankaceratops",
      "Hanwulosaurus",
      "Gryphoceratops",
      "Linheraptor",
      "Ornithomimoides",
      "Edmontonia",
      "Aerosteon",
      "Ninghsiasaurus",
      "Prenoceratops",
      "Vagaceratops",
      "Sinucerasaurus",
      "Hongshanosaurus",
      "Hexinlusaurus",
      "Indosuchus",
      "Moshisaurus",
      "Alashansaurus",
      "Berberosaurus",
      "Elaltitan",
      "Marisaurus",
      "Rhoetosaurus",
      "Tatankacephalus",
      "Bienosaurus",
      "Dracopelta",
      "Chiayusaurus",
      "Pseudosuchia",
      "Sarcosaurus",
      "Shuvuuia",
      "Unaysaurus",
      "Amtosaurus",
      "Nqwebasaurus",
      "Claorhynchus",
      "Prolacertiform",
      "Honghesaurus",
      "Ugrosaurus",
      "Aegyptosaurus",
      "Gallimimus",
      "Clasmodosaurus",
      "Hypacrosaurus",
      "Caenagnathus",
      "Velocipes",
      "Lessemsaurus",
      "Agrosaurus",
      "Paronychodon",
      "Maleevosaurus",
      "Leipsanosaurus",
      "Clevelanotyrannus",
      "Dynamosaurus",
      "Megacervixosaurus",
      "Protohadros",
      "Polyonax",
      "Daxiatitan",
      "Spondylosoma",
      "Ichthyovenator",
      "Demandasaurus",
      "Dimodosaurus",
      "Torvosaurus",
      "Gwyneddosaurus",
      "Cystosaurus",
      "Irritator",
      "Zanclodon",
      "Rugops",
      "Ignavusaurus",
      "Chinshakiangosaurus",
      "Zhejiangosaurus",
      "Pachyrhinosaurus",
      "Stenotholus",
      "Iuticosaurus",
      "Tyrannotitan",
      "Xixianykus",
      "Palaeopteryx",
      "Vitakridrinda",
      "Planicoxa",
      "Jianchangosaurus",
      "Sinovenator",
      "Ohmdenosaurus",
      "Protecovasaurus",
      "Eoceratops",
      "Laevisuchus",
      "Cumnoria",
      "Ratchasimasaurus",
      "Elaphrosaurus",
      "Dracovenator",
      "Abelisaurus",
      "Sangonghesaurus",
      "Austrocheirus",
      "Calamosaurus",
      "Vectensia",
      "Elosaurus",
      "Termatosaurus",
      "Pleuropeltus",
      "Chubutisaurus",
      "Macrophalangia",
      "Futalongkosaurus",
      "Acristavus",
      "Wintonotitan",
      "Diclonius",
      "Nanosaurus",
      "Tonganosaurus",
      "Tarascosaurus",
      "Amphicoelicaudia",
      "Achillesaurus",
      "Delapparentia",
      "Argentinosaurus",
      "Sulaimansaurus",
      "Koparion",
      "Brachytrachelopan",
      "Bakesaurus",
      "Rahona",
      "Oryctodromeus",
      "Campylodon",
      "Stygivenator",
      "Wangonisaurus",
      "Genyodectes",
      "Acrocanthosaurus",
      "Danubiosaurus",
      "Deltadromeus",
      "Rileya",
      "Borealosaurus",
      "Rioarribasaurus",
      "Gondwanatitan",
      "Lophorhothon",
      "Talenkauen",
      "Diracodon",
      "Nanshiungosaurus",
      "Bradycneme",
      "Ferganocephale",
      "Cheneosaurus",
      "Wulagasaurus",
      "Tanystrosuchus",
      "Comahuesaurus",
      "Actiosaurus",
      "Jiangjunmiaosaurus",
      "Xinjiangovenator",
      "Gadolosaurus",
      "Clarencea",
      "Avemetatarsalia",
      "Dakotadon",
      "Diapsid",
      "Albinykus",
      "Pectinodon",
      "Protorosaurus",
      "Ginnareemimus",
      "Doryphorosaurus",
      "Dalianraptor",
      "Megapnosaurus",
      "Scelidosaurus",
      "Metriorhynchid",
      "Piatnitzkysaurus",
      "Haplocanthosaurus",
      "Phytosaur",
      "Manospondylus",
      "Gansutitan",
      "Neovenator",
      "Brasileosaurus",
      "Judiceratops",
      "Khetranisaurus",
      "Fish",
      "Proceratosaurus",
      "Zatomus",
      "Ceratosaurus",
      "Unescoceratops",
      "Telmatosaurus",
      "Segisaurus",
      "Pachyspondylus",
      "Caseosaurus",
      "Ultrasauros",
      "Dongbeititan",
      "Galvesaurus",
      "Crocodylomorph",
      "Ephoenosaurus",
      "Fossil",
      "Crosbysaurus",
      "Coelosaurus",
      "Unenlagia",
      "Strenusaurus",
      "Concavenator",
      "Fukuiraptor",
      "Camarasaurus",
      "Iliosuchus",
      "Huayangosaurus",
      "Kileskus",
      "Clepsysaurus",
      "Richardoestesia",
      "Sphenosaurus",
      "Scutellosaurus",
      "Garudimimus",
      "Hexing",
      "Nanningosaurus",
      "Sonorasaurus",
      "Pradhania",
      "Orosaurus",
      "Andesaurus",
      "Genusaurus",
      "Huxleysaurus",
      "Elopteryx",
      "Alectrosaurus",
      "Tecovasaurus",
      "Parksosaurus",
      "Paranthodon",
      "Airakoraptor",
      "Jobaria",
      "Ichabodcraniosaurus",
      "Muyelensaurus",
      "Sacisaurus",
      "Deinodon",
      "Patricosaurus",
      "Maleevus",
      "Tylocephale",
      "Sugiyamasaurus",
      "Nodosaurus",
      "Aliwalia",
      "Kerberosaurus",
      "Kazaklambia",
      "Eolambia",
      "Dongyangosaurus",
      "Citipati",
      "Euskelosaurus",
      "Trigonosaurus",
      "Epidexipteryx",
      "Dolichosuchus",
      "Walkeria",
      "Labrosaurus",
      "Condorraptor",
      "Tichosteus",
      "Uberabatitan",
      "Magnosaurus",
      "Janenschia",
      "Anasazisaurus",
      "Macrogryphosaurus",
      "Erliansaurus",
      "Ornithotarsus",
      "Bayosaurus",
      "Santanaraptor",
      "Zhuchengtyrannus",
      "Lukousaurus",
      "Sauroposeidon",
      "Ampelosaurus",
      "Pampadromaeus",
      "Erectopus",
      "Glyptodontopelta",
      "Drinker",
      "Leaellynasaura",
      "Magyarosaurus",
      "Postosuchus",
      "Szechuanoraptor",
      "Yubasaurus",
      "Brachyrophus",
      "Cionodon",
      "Sellacoxa",
      "Elachistosuchus",
      "Shuvosaurus",
      "Sauraechmodon",
      "Microdontosaurus",
      "Carcharodontosaurus",
      "Brachylophosaurus",
      "Theropoda",
      "Tapinocephalus",
      "Changchunsaurus",
      "Cladeiodon",
      "Pareiasaurus",
      "Heishansaurus",
      "Aristosuchus",
      "Protiguanodon",
      "Brohisaurus",
      "Eupodosaurus",
      "Datousaurus",
      "Giraffatitan",
      "Jaklapallisaurus",
      "Tugulusaurus",
      "Compsognathus",
      "Ilokelesia",
      "Revueltoraptor",
      "Tuojiangosaurus",
      "Huaxiasaurus",
      "Palaeocursornis",
      "Onychosaurus",
      "Ceratonykus",
      "Amargatitanis",
      "Albalophosaurus",
      "Byronosaurus",
      "Cryptovolans",
      "Shenzhousaurus",
      "Rapetosaurus",
      "Altirhinus",
      "Sanjuansaurus",
      "Dysalotosaurus",
      "Archaeopteryx",
      "Liliensternus",
      "Beelemodon",
      "Xuanhuaceratops",
      "Protrachodon",
      "Caenagnathasia",
      "Willinakaqe",
      "Atacamatitan",
      "Lourinhanosaurus",
      "Yaverlandia",
      "Ligomasaurus",
      "Suchomimus",
      "Brasilotitan",
      "Jenghizkhan",
      "Aggiosaurus",
      "Elrhazosaurus",
      "Yingshanosaurus",
      "Australovenator",
      "Ichthyornis",
      "Valdosaurus",
      "Yuanmouraptor",
      "Prolacertiformes",
      "Tarchia",
      "Hesperosaurus",
      "Azendohsaurus",
      "Eucentrosaurus",
      "Scipionyx",
      "Petrobrasaurus",
      "Hudiesaurus",
      "Sinornithosaurus",
      "Shuangmiaosaurus",
      "Tianchisaurus",
      "Araucanoraptor",
      "Poposaurus",
      "Pararhabdodon",
      "Osmakasaurus",
      "Siamotyrannus",
      "Galveosaurus",
      "Yangchuanosaurus",
      "Microcephale",
      "Mirischia",
      "Probactrosaurus",
      "Yunxiansaurus",
      "Enantiornithine",
      "Cedrorestes",
      "Chaoyangsaurus",
      "Loricatosaurus",
      "Stygimoloch",
      "Venaticosuchus",
      "Gorgosaurus",
      "Anchiornis",
      "Ischisaurus",
      "Bactrosaurus",
      "Quilmesaurus",
      "Fukuisaurus",
      "Stegosaurus",
      "Griphosaurus",
      "Graciliceratops",
      "Oligosaurus",
      "Baotianmansaurus",
      "Eocursor",
      "Turtle",
      "Macelognathus",
      "Arctosaurus",
      "Streptospondylus",
      "Texasetes",
      "Dianchungosaurus",
      "Birds",
      "Nomingia",
      "Sinornithomimus",
      "Hierosaurus",
      "Abdallahsaurus",
      "Jaxartosaurus",
      "Sanchusaurus",
      "Tarbosaurus",
      "Sinocoelurus",
      "Timimus",
      "Herrerasaurus",
      "Giganotosaurus",
      "Tsaagan",
      "Anthracothere",
      "Yezosaurus",
      "Chihuahuasaurus",
      "Cathartesaura",
      "Domeykosaurus",
      "Loncosaurus",
      "Archaeoceratops",
      "Udanoceratops",
      "Gojirasaurus",
      "Dongyangopelta",
      "Duriatitan",
      "Chondrosteus",
      "Arkanosaurus",
      "Lusotitan",
      "Diceratus",
      "Nuoersaurus",
      "Wadhurstia",
      "Sauropelta",
      "Ultrasaurus",
      "Indosaurus",
      "Kotasaurus",
      "Urbacodon",
      "Zhongyuansaurus",
      "Tanystropheus",
      "Mifunesaurus",
      "Pegomastax",
      "Gobititan",
      "Lusitanosaurus",
      "Caulodon",
      "Baryonyx",
      "Tataouinea",
      "Longosaurus",
      "Pareiasaur",
      "Leshansaurus",
      "Machairasaurus",
      "Colossosaurus",
      "Arstanosaurus",
      "Wakinosaurus",
      "Lanasaurus",
      "Dryosaurus",
      "Sterrholophus",
      "Dachungosaurus",
      "Chialingosaurus",
      "Jiangjunosaurus",
      "Klamelisaurus",
      "Rauisuchia",
      "Caudipteryx",
      "Jinfengopteryx",
      "Leptoceratops",
      "Sinotyrannus",
      "Poekilopleuron",
      "Gobisaurus",
      "Angaturama",
      "Pterosaur",
      "Aetonyx",
      "Angolatitan",
      "Tanius",
      "Therizinosaurus",
      "Tastavinsaurus",
      "Lancangosaurus",
      "Dinheirosaurus",
      "Brachypodosaurus",
      "Gobiceratops",
      "Fruitadens",
      "Monkonosaurus",
      "Spinostropheus",
      "Cristatusaurus",
      "Bolong",
      "Rebbachisaurus",
      "Monolophosaurus",
      "Alioramus",
      "Hypsirophus",
      "Olorotitan",
      "Euoplocephalus",
      "Juravenator",
      "Euhelopus",
      "Epanterias",
      "Lancanjiangosaurus",
      "Xianshanosaurus",
      "Ekrixinatosaurus",
      "Achillobator",
      "Hesperonychus",
      "Pachysauriscus",
      "Ruyangosaurus",
      "Gongbusaurus",
      "Teratosaurus",
      "Ruehleia",
      "Yaleosaurus",
      "Canardia",
      "Brachyceratops",
      "Pantydraco",
      "Afrovenator",
      "Mendozasaurus",
      "Pedopenna",
      "Blasisaurus",
      "Astrodon",
      "Mandschurosaurus",
      "Drusilasaura",
      "Libycosaurus",
      "Eucamerotus",
      "Tonouchisaurus",
      "Didanodon",
      "Proplanicoxa",
      "Kentrurosaurus",
      "Trinisaura",
      "Fusuisaurus",
      "Kentrosaurus",
      "Eocarcharia",
      "Albertaceratops",
      "Rutellum",
      "Saltasaurus",
      "Majungatholus",
      "Mussaurus",
      "Zigongosaurus",
      "Euacanthus",
      "Craspedodon",
      "Ingenia",
      "Priodontognathus",
      "Rubeosaurus",
      "Gyposaurus",
      "Utahraptor",
      "Pukyongosaurus",
      "Coelurosaur",
      "Silvisaurus",
      "Troodon",
      "Jixiangornis",
      "Pawpawsaurus",
      "Oohkotokia",
      "Hadrosauravus",
      "Shaochilong",
      "Ponerosteus",
      "Ischyrosaurus",
      "Hadrosaurus",
      "Gryposaurus",
      "Spinops",
      "Peloroplites",
      "Daspletosaurus",
      "Dravidosaurus",
      "Hagryphus",
      "Sphenosuchia",
      "Ligabueino",
      "Mymoorapelta",
      "Tatisaurus",
      "Trimucrodon",
      "Cathetosaurus",
      "Teinurosaurus",
      "Antetonitrus",
      "Rajasaurus",
      "Fabrosaurus",
      "Angloposeidon",
      "Levnesovia",
      "Mongolosaurus",
      "Asiaceratops",
      "Avipes",
      "Turiasaurus",
      "Eucnemesaurus",
      "Otogosaurus",
      "Martharaptor",
      "Tsintaosaurus",
      "Hypsilophodon",
      "Gigantoscelus",
      "Palaeosauriscus",
      "Hironosaurus",
      "Paludititan",
      "Anatosaurus",
      "Kaatedocus",
      "Linhevenator",
      "Pellegrinisaurus",
      "Sanpasaurus",
      "Lapampasaurus",
      "Inosaurus",
      "Eomamenchisaurus",
      "Liassaurus",
      "Jinzhousaurus",
      "Equijubus",
      "Dryptosaurus",
      "Nopcsaspondylus",
      "Changtusaurus",
      "Tapuiasaurus",
      "Diabloceratops",
      "Dakosaurus",
      "Chassternbergia",
      "Limaysaurus",
      "Huaxiaosaurus",
      "Minotaurasaurus",
      "Uteodon",
      "Micropachycephalosaurus",
      "Avisaurus",
      "Siamodon",
      "Ornithomerus",
      "Eodromaeus",
      "Turanoceratops",
      "Nambalia",
      "Cruxicheiros",
      "Riojasuchus",
      "Stokesosaurus",
      "Amygdalodon",
      "Linhenykus",
      "Heterodontosaurus",
      "Dromicosaurus",
      "Bahariasaurus",
      "Xiongguanlong",
      "Jeyawati",
      "Polyodontosaurus",
      "Morinosaurus",
      "Campylodoniscus",
      "Aralosaurus",
      "Pentaceratops",
      "Squalodon",
      "Saurornitholestes",
      "Yandusaurus",
      "Bruhathkayosaurus",
      "Kinnareemimus",
      "Tornieria",
      "Scaphonyx",
      "Barosaurus",
      "Titanosaurus",
      "Volkheimeria",
      "Brontomerus",
      "Megalosaurus",
      "Rhopalodon",
      "Huanghetitan",
      "Ngexisaurus",
      "Jiangshanosaurus",
      "Archosaur",
      "Sciurumimus",
      "Histriasaurus",
      "Spinosaurus",
      "Eoraptor",
      "Phaedrolosaurus",
      "Betasuchus",
      "Belodon",
      "Bagaraatan",
      "Protognathus",
      "Marmarospondylus",
      "Dinosaur",
      "Darwinsaurus",
      "Apatodon",
      "Eotyrannus",
      "Struthiomimus",
      "Pelecanimimus",
      "Gideonmantellia",
      "Appalachiosaurus",
      "Edmontosaurus",
      "Acracanthus",
      "Machimosaurus",
      "Razanandrongobe",
      "Uintasaurus",
      "Magnapaulia",
      "Moabosaurus",
      "Ojoceratops",
      "Yaxartosaurus",
      "Macroscelosaurus",
      "Aniksosaurus",
      "Guanlong",
      "Futabasaurus",
      "Proceratops",
      "Xuwulong",
      "Ricardoestesia",
      "Symphyrophus",
      "Pleurocoelus",
      "Damalasaurus",
      "Naashoibitosaurus",
      "Panphagia",
      "Graciliraptor",
      "Ornithoides",
      "Futalognkosaurus",
      "Pachycephalosaurus",
      "Plesiosaur",
      "Astrophocaudia",
      "Gilmoreosaurus",
      "Diamantinasaurus",
      "Eucercosaurus",
      "Gavinosaurus",
      "Suchosaurus",
      "Eugongbusaurus",
      "Camelotia",
      "Shanxia",
      "Antarctopelta",
      "Traukutitan",
      "Saurornithoides",
      "Hippodraco",
      "Nteregosaurus",
      "Sauropodus",
      "Coelurosauravus",
      "Stereocephalus",
      "Adeopapposaurus",
      "Ctenosauriscid",
      "Paraiguanodon",
      "Eosinopteryx",
      "Archaeornis",
      "Bambiraptor",
      "Isanosaurus",
      "Stegosaurides",
      "Avaceratops",
      "Gannansaurus",
      "Triceratops",
      "Paluxysaurus",
      "Denversaurus",
      "Bathygnathus",
      "Katsuyamasaurus",
      "Barsboldia",
      "Mojoceratops",
      "Eucoelophysis",
      "Microraptor",
      "Calamospondylus",
      "Fusinasus",
      "Agathaumas",
      "Protoceratops",
      "Eustreptospondylus",
      "Macrurosaurus",
      "Atlascopcosaurus",
      "Claosaurus",
      "Avicephala",
      "Tochisaurus",
      "Protognathosaurus",
      "Kakuru",
      "Neuquensaurus",
      "Chilantaisaurus",
      "Chindesaurus",
      "Parvicursor",
      "Phuwiangosaurus",
      "Saltriosaurus",
      "Edmarka",
      "Chingkankousaurus",
      "Bicentenaria",
      "Kemkemia",
      "Microceratus",
      "Chaoyangosaurus",
      "Atlasaurus",
      "Eotriceratops",
      "Neimongosaurus",
      "Unicerosaurus",
      "Qinlingosaurus",
      "Laosaurus",
      "Craterosaurus",
      "Dacentrurus",
      "Geminiraptor",
      "Erlikosaurus",
      "Bonitasaura",
      "Arrhinoceratops",
      "Triassolestes",
      "Hisanohamasaurus",
      "Oplosaurus",
      "Supersaurus",
      "Achelousaurus",
      "Rinconsaurus",
      "Serendipaceratops",
      "Eoabelisaurus",
      "Dystrophaeus",
      "Thotobolosaurus",
      "Blancocerosaurus",
      "Cetiosaurus",
      "Roccosaurus",
      "Chondrosteosaurus",
      "Fulengia",
      "Mohammadisaurus",
      "Halticosaurus",
      "Lancangjiangosaurus",
      "Teyuwasu",
      "Breviceratops",
      "Rhodanosaurus",
      "Metriacanthosaurus",
      "Overosaurus",
      "Newtonsaurus",
      "Gracilisuchus",
      "Pseudolagosuchus",
      "Sellosaurus",
      "Ajkaceratops",
      "Lufengosaurus",
      "Yamaceratops",
      "Bagaceratops",
      "Apatosaurus",
      "Khateranisaurus",
      "Batyrosaurus",
      "Cinizasaurus",
      "Tanycolagreus",
      "Bainoceratops",
      "Silesaurid",
      "Byranjaffia",
      "Shamosaurus",
      "Austrosaurus",
      "Amtocephale",
      "Cylindricodon",
      "Huabeisaurus",
      "Regnosaurus",
      "Callovosaurus",
      "Heptasteornis",
      "Gryponyx",
      "Tylosteus",
      "Gargoyleosaurus",
      "Kundurosaurus",
      "Mononykus",
      "Secernosaurus",
      "Puertasaurus",
      "Bellusaurus",
      "Archosauriform",
      "Qiupalong",
      "Alamosaurus",
      "Dystylosaurus",
      "Tethyshadros",
      "Selimanosaurus",
      "Albertadromeus",
      "Karongasaurus",
      "Kaijiangosaurus",
      "Microvenator",
      "Amphicoelias",
      "Eshanosaurus",
      "Salimosaurus",
      "Avimimus",
      "Elvisaurus",
      "Bonatitan",
      "Procheneosaurus",
      "Tetragonosaurus",
      "Mammal",
      "Oshanosaurus",
      "Jurapteryx",
      "Paleosaurus",
      "Dinosauromorph",
      "Plateosauravus",
      "Hungarosaurus",
      "Chromogisaurus",
      "Anoplosaurus",
      "Amargasaurus",
      "Merosaurus",
      "Alwalkeria",
      "Macrodontophion",
      "Shanshanosaurus",
      "Gongxianosaurus",
      "Vectisaurus",
      "Kitadanisaurus",
      "Agustinia",
      "Sulaimanisaurus",
      "Thescelosaurus",
      "Zephyrosaurus",
      "Arenysaurus",
      "Patagosaurus",
      "Laornis",
      "Protoavis",
      "Tenantosaurus",
      "Yinlong",
      "Bravoceratops",
      "Saurophaganax",
      "Coeluroides",
      "Seitaad",
      "Trialestes",
      "Glishades",
      "Cedarpelta",
      "Rinchenia",
      "Lesothosaurus",
      "Dromaeosaur",
      "Nuoerosaurus",
      "Hallopus",
      "Yanornis",
      "Tomodon",
      "Juratyrant",
      "Shanyangosaurus",
      "Deuterosaurus",
      "Coelurus",
      "Zizhongosaurus",
      "Hypselospinus",
      "Austroraptor",
      "Brachytaenius",
      "Orcomimus",
      "Acrotholus",
      "Chirostenotes",
      "Emausaurus",
      "Nigersaurus",
      "Animantarx",
      "Luanchuanraptor",
      "Zuniceratops",
      "Wannanosaurus",
      "Abrictosaurus",
      "Heyuannia",
      "Synapsid",
      "Struthiosaurus",
      "Yunnanosaurus",
      "Noasaurus",
      "Tyrannosaurid",
      "Yibinosaurus",
      "Thespesius",
      "Priconodon",
      "Marasuchus",
      "Anchisaurus",
      "Iguanacolossus",
      "Patagonykus",
      "Haplocanthus",
      "Corythosaurus",
      "Limusaurus",
      "Coloradisaurus",
      "Similicaudipteryx",
      "Leptospondylus",
      "Aviatyrannis",
      "Hortalotarsus",
      "Tienshanosaurus",
      "Pamparaptor",
      "Peishansaurus",
      "Succinodon",
      "Dinosaurus",
      "Rachitrema",
      "Dachongosaurus",
      "Therapsida",
      "Saurolophus",
      "Pekinosaurus",
      "Skorpiovenator",
      "Microsaurops",
      "Ammosaurus",
      "Ichthyosaur",
      "Antarctosaurus",
      "Liaoningosaurus",
      "Nothronychus",
      "Spinosuchus",
      "Iguanosaurus",
      "Anchiceratops",
      "Orkoraptor",
      "Microcoelus",
      "Xuanhanosaurus",
      "Geranosaurus",
      "Goyocephale",
      "Ankylosauria",
      "Dahalokely",
      "Daptosaurus",
      "Loricosaurus",
      "Australodocus",
      "Pterospondylus",
      "Gigantoraptor",
      "Hylaeosaurus",
      "Caudocoelus",
      "Opisthocoelicaudia",
      "Rhadinosaurus",
      "Ligabuesaurus",
      "Aragosaurus",
      "Rocasaurus",
      "Parrosaurus",
      "Sahaliyania",
      "Agilisaurus",
      "Orthomerus",
      "Penelopognathus",
      "Liaoceratops",
      "Dyoplosaurus",
      "Stenonychosaurus",
      "Walkersaurus",
      "Narambuenatitan",
      "Pitekunsaurus",
      "Camarillasaurus",
      "Procolophonid",
      "Epichirostenotes",
      "Beishanlong",
      "Gasosaurus",
      "Coronosaurus",
      "Zapalasaurus",
      "Sauraechinodon",
      "Glacialisaurus",
      "Therapsid",
      "Gravisaurus",
      "Lewisuchus",
      "Jainosaurus",
      "Centemodon",
      "Arkansaurus",
      "Einiosaurus",
      "Palaeoscincus",
      "Cerasinops",
      "Microceratops",
      "Pteropelyx",
      "Sigilmassasaurus",
      "Staurikosaurus",
      "Pyroraptor",
      "Ornithodesmus",
      "Asylosaurus",
      "Anodontosaurus",
      "Siluosaurus",
      "Carnosauria",
      "Qantassaurus",
      "Ornithomimus",
      "Dinodocus",
      "Chuxiongosaurus",
      "Anserimimus",
      "Camptonotus",
      "Lagosuchus",
      "Anatotitan",
      "Dryptosauroides",
      "Silesaurus",
      "Pachysaurops",
      "Saichania",
      "Procerosaurus",
      "Lucianosaurus",
      "Koreasaurus",
      "Lurdusaurus",
      "Piveteausaurus",
      "Jeholornis",
      "Angulomastacator",
      "Hoplosaurus",
      "Saltopus",
      "Shanag",
      "Homalocephale",
      "Torosaurus",
      "Fenestrosaurus",
      "Jubbulpuria",
      "Mtotosaurus",
      "Nemegtosaurus",
      "Maiasaura",
      "Yutyrannus",
      "Ozraptor",
      "Lariosaurus",
      "Bugenasaura",
      "Ornatotholus",
      "Aardonyx",
      "Herbstosaurus",
      "Tianyuraptor",
      "Diplodocus",
      "Kosmoceratops",
      "Muttaburrasaurus",
      "Kagasaurus",
      "Atsinganosaurus",
      "Massospondylus",
      "Utahceratops",
      "Nanotyrannus",
      "Qingxiusaurus",
      "Avalonianus",
      "Erketu",
      "Fulgurotherium",
      "Kayentavenator",
      "Protarchaeopteryx",
      "Chungkingosaurus",
      "Krzyzanowskisaurus",
      "Yimenosaurus",
      "Aurornis",
      "Ganzhousaurus",
      "Pinacosaurus",
      "Archosauromorph",
      "Niobrarasaurus",
      "Melanorosaurus",
      "Baurutitan",
      "Elmisaurus",
      "Euronychodon",
      "Tehuelchesaurus",
      "Sinusonasus",
      "Omeisaurus",
      "Agujaceratops",
      "Aucasaurus",
      "Wulatelong",
      "Stegopelta",
      "Europasaurus",
      "Alxasaurus",
      "Stegosauroides",
      "Tangvayosaurus",
      "Pliosaur",
      "Unquillosaurus",
      "Xixiposaurus",
      "Ornithopsis",
      "Crataeomus",
      "Madsenius",
      "Diplotomodon",
      "Kulceratops",
      "Adamantisaurus",
      "Nyororosaurus",
      "Monoclonius",
      "Kuszholia",
      "Jintasaurus",
      "Camptosaurus",
      "Masiakasaurus",
      "Parhabdodon",
      "Prodeinodon",
      "Saurophagus",
      "Alvarezsaurus",
      "Mantellisaurus",
      "Aristosaurus",
      "Suzhousaurus",
      "Limnosaurus",
      "Dromaeosauroides",
      "Augustia",
      "Spinosaurid",
      "Othnielia",
      "Thecospondylus",
      "Cetacea",
      "Medusaceratops",
      "Zalmoxes",
      "Koreaceratops",
      "Syngonosaurus",
      "Dicraeosaurus",
      "Xenoceratops",
      "Scleromochlus",
      "Deinocheirus",
      "Chuandongocoelurus",
      "Itemirus",
      "Phyllodon",
      "Megaraptor",
      "Philovenator",
      "Ferganasaurus",
      "Pelorosaurus",
      "Nebulasaurus",
      "Barilium",
      "Nedoceratops",
      "Acanthopholis",
      "Nuthetes",
      "Panoplosaurus",
      "Quaesitosaurus",
      "Crocodile",
      "Archaeoraptor",
      "Charonosaurus",
      "Eureodon",
      "Hanssuesia",
      "Guaibasaurus",
      "Camposaurus",
      "Hylosaurus",
      "Zapsalis",
      "Bistahieversor",
      "Erlicosaurus",
      "Procompsognathus",
      "Hypselosaurus",
      "Prenocephale",
      "Malarguesaurus",
      "Tenontosaurus",
      "Kittysaurus",
      "Iguanodon",
      "Palaeoctonus",
      "Trachodon",
      "Wyomingraptor",
      "Huehuecanauhtlus",
      "Theiophytalia",
      "Nectosaurus",
      "Scolosaurus",
      "Pisanosaurus",
      "Kunmingosaurus",
      "Liubangosaurus",
      "Malawisaurus",
      "Pakisaurus",
      "Carnosaur",
      "Leonerasaurus",
      "Oviraptor",
      "Texacephale",
      "Shantungosaurus",
      "Zhuchengosaurus",
      "Gripposaurus",
      "Polacanthus",
      "Xenotarsosaurus",
      "Dinosauriform",
      "Hypsibema",
      "Podokesaurus",
      "Sonidosaurus",
      "Colepiocephale",
      "Kelmayisaurus",
      "Crichtonsaurus",
      "Stegoceras",
      "Borogovia",
      "Lourinhasaurus",
      "Picrodon",
      "Mononychus",
      "Bothriospondylus",
      "Siamosaurus",
      "Technosaurus",
      "Theropod",
      "Neosodon",
      "Velociraptor",
      "Eolosaurus",
      "Archaeovolans",
      "Chebsaurus",
      "Compsosuchus",
      "Othnielosaurus",
      "Banji",
      "Proiguanodon",
      "Rahonavis",
      "Majungasaurus",
      "Nanotyrannosaurus",
      "Bissektipelta",
      "Revueltosaurus",
      "Lexovisaurus",
      "Antrodemus",
      "Hikanodon",
      "Tyrannosaurus",
      "Barrosasaurus",
      "Sinoceratops",
      "Megadontosaurus",
      "Sinosauropteryx",
      "Heilongjiangosaurus",
      "Maxakalisaurus",
      "Jensenosaurus",
      "Dandakosaurus",
      "Therosaurus",
      "Sarahsaurus",
      "Hypselorhachis",
      "Archaeodontosaurus",
      "Gresslyosaurus",
      "Stenopelix"
    ],
  "dogs":
    [
      "Affenpinscher",
      "Afghan Hound",
      "Aidi",
      "Airedale Terrier",
      "Akbash Dog",
      "Akita",
      "Alano Español",
      "Alaskan Klee Kai",
      "Alaskan Malamute",
      "Alpine Dachsbracke",
      "Alpine Spaniel",
      "American Bulldog",
      "American Cocker Spaniel",
      "American Eskimo Dog",
      "American Foxhound",
      "American Hairless Terrier",
      "American Pit Bull Terrier",
      "American Staffordshire Terrier",
      "American Water Spaniel",
      "Anglo-Français de Petite Vénerie",
      "Appenzeller Sennenhund",
      "Ariege Pointer",
      "Ariegeois",
      "Armant",
      "Armenian Gampr dog",
      "Artois Hound",
      "Australian Cattle Dog",
      "Australian Kelpie",
      "Australian Shepherd",
      "Australian Silky Terrier",
      "Australian Stumpy Tail Cattle Dog",
      "Australian Terrier",
      "Azawakh",
      "Bakharwal Dog",
      "Barbet",
      "Basenji",
      "Basque Shepherd Dog",
      "Basset Artésien Normand",
      "Basset Bleu de Gascogne",
      "Basset Fauve de Bretagne",
      "Basset Hound",
      "Bavarian Mountain Hound",
      "Beagle",
      "Beagle-Harrier",
      "Bearded Collie",
      "Beauceron",
      "Bedlington Terrier",
      "Belgian Shepherd Dog (Groenendael)",
      "Belgian Shepherd Dog (Laekenois)",
      "Belgian Shepherd Dog (Malinois)",
      "Bergamasco Shepherd",
      "Berger Blanc Suisse",
      "Berger Picard",
      "Berner Laufhund",
      "Bernese Mountain Dog",
      "Billy",
      "Black and Tan Coonhound",
      "Black and Tan Virginia Foxhound",
      "Black Norwegian Elkhound",
      "Black Russian Terrier",
      "Bloodhound",
      "Blue Lacy",
      "Blue Paul Terrier",
      "Boerboel",
      "Bohemian Shepherd",
      "Bolognese",
      "Border Collie",
      "Border Terrier",
      "Borzoi",
      "Boston Terrier",
      "Bouvier des Ardennes",
      "Bouvier des Flandres",
      "Boxer",
      "Boykin Spaniel",
      "Bracco Italiano",
      "Braque d'Auvergne",
      "Braque du Bourbonnais",
      "Braque du Puy",
      "Braque Francais",
      "Braque Saint-Germain",
      "Brazilian Terrier",
      "Briard",
      "Briquet Griffon Vendéen",
      "Brittany",
      "Broholmer",
      "Bruno Jura Hound",
      "Bucovina Shepherd Dog",
      "Bull and Terrier",
      "Bull Terrier (Miniature)",
      "Bull Terrier",
      "Bulldog",
      "Bullenbeisser",
      "Bullmastiff",
      "Bully Kutta",
      "Burgos Pointer",
      "Cairn Terrier",
      "Canaan Dog",
      "Canadian Eskimo Dog",
      "Cane Corso",
      "Cardigan Welsh Corgi",
      "Carolina Dog",
      "Carpathian Shepherd Dog",
      "Catahoula Cur",
      "Catalan Sheepdog",
      "Caucasian Shepherd Dog",
      "Cavalier King Charles Spaniel",
      "Central Asian Shepherd Dog",
      "Cesky Fousek",
      "Cesky Terrier",
      "Chesapeake Bay Retriever",
      "Chien Français Blanc et Noir",
      "Chien Français Blanc et Orange",
      "Chien Français Tricolore",
      "Chien-gris",
      "Chihuahua",
      "Chilean Fox Terrier",
      "Chinese Chongqing Dog",
      "Chinese Crested Dog",
      "Chinese Imperial Dog",
      "Chinook",
      "Chippiparai",
      "Chow Chow",
      "Cierny Sery",
      "Cimarrón Uruguayo",
      "Cirneco dell'Etna",
      "Clumber Spaniel",
      "Combai",
      "Cordoba Fighting Dog",
      "Coton de Tulear",
      "Cretan Hound",
      "Croatian Sheepdog",
      "Cumberland Sheepdog",
      "Curly Coated Retriever",
      "Cursinu",
      "Cão da Serra de Aires",
      "Cão de Castro Laboreiro",
      "Cão Fila de São Miguel",
      "Dachshund",
      "Dalmatian",
      "Dandie Dinmont Terrier",
      "Danish Swedish Farmdog",
      "Deutsche Bracke",
      "Doberman Pinscher",
      "Dogo Argentino",
      "Dogo Cubano",
      "Dogue de Bordeaux",
      "Drentse Patrijshond",
      "Drever",
      "Dunker",
      "Dutch Shepherd Dog",
      "Dutch Smoushond",
      "East Siberian Laika",
      "East-European Shepherd",
      "Elo",
      "English Cocker Spaniel",
      "English Foxhound",
      "English Mastiff",
      "English Setter",
      "English Shepherd",
      "English Springer Spaniel",
      "English Toy Terrier (Black &amp; Tan)",
      "English Water Spaniel",
      "English White Terrier",
      "Entlebucher Mountain Dog",
      "Estonian Hound",
      "Estrela Mountain Dog",
      "Eurasier",
      "Field Spaniel",
      "Fila Brasileiro",
      "Finnish Hound",
      "Finnish Lapphund",
      "Finnish Spitz",
      "Flat-Coated Retriever",
      "Formosan Mountain Dog",
      "Fox Terrier (Smooth)",
      "French Bulldog",
      "French Spaniel",
      "Galgo Español",
      "Gascon Saintongeois",
      "German Longhaired Pointer",
      "German Pinscher",
      "German Shepherd",
      "German Shorthaired Pointer",
      "German Spaniel",
      "German Spitz",
      "German Wirehaired Pointer",
      "Giant Schnauzer",
      "Glen of Imaal Terrier",
      "Golden Retriever",
      "Gordon Setter",
      "Gran Mastín de Borínquen",
      "Grand Anglo-Français Blanc et Noir",
      "Grand Anglo-Français Blanc et Orange",
      "Grand Anglo-Français Tricolore",
      "Grand Basset Griffon Vendéen",
      "Grand Bleu de Gascogne",
      "Grand Griffon Vendéen",
      "Great Dane",
      "Great Pyrenees",
      "Greater Swiss Mountain Dog",
      "Greek Harehound",
      "Greenland Dog",
      "Greyhound",
      "Griffon Bleu de Gascogne",
      "Griffon Bruxellois",
      "Griffon Fauve de Bretagne",
      "Griffon Nivernais",
      "Hamiltonstövare",
      "Hanover Hound",
      "Hare Indian Dog",
      "Harrier",
      "Havanese",
      "Hawaiian Poi Dog",
      "Himalayan Sheepdog",
      "Hokkaido",
      "Hovawart",
      "Huntaway",
      "Hygenhund",
      "Ibizan Hound",
      "Icelandic Sheepdog",
      "Indian pariah dog",
      "Indian Spitz",
      "Irish Red and White Setter",
      "Irish Setter",
      "Irish Terrier",
      "Irish Water Spaniel",
      "Irish Wolfhound",
      "Istrian Coarse-haired Hound",
      "Istrian Shorthaired Hound",
      "Italian Greyhound",
      "Jack Russell Terrier",
      "Jagdterrier",
      "Jämthund",
      "Kai Ken",
      "Kaikadi",
      "Kanni",
      "Karelian Bear Dog",
      "Karst Shepherd",
      "Keeshond",
      "Kerry Beagle",
      "Kerry Blue Terrier",
      "King Charles Spaniel",
      "King Shepherd",
      "Kintamani",
      "Kishu",
      "Komondor",
      "Kooikerhondje",
      "Koolie",
      "Korean Jindo Dog",
      "Kromfohrländer",
      "Kumaon Mastiff",
      "Kurī",
      "Kuvasz",
      "Kyi-Leo",
      "Labrador Husky",
      "Labrador Retriever",
      "Lagotto Romagnolo",
      "Lakeland Terrier",
      "Lancashire Heeler",
      "Landseer",
      "Lapponian Herder",
      "Large Münsterländer",
      "Leonberger",
      "Lhasa Apso",
      "Lithuanian Hound",
      "Longhaired Whippet",
      "Löwchen",
      "Mahratta Greyhound",
      "Maltese",
      "Manchester Terrier",
      "Maremma Sheepdog",
      "McNab",
      "Mexican Hairless Dog",
      "Miniature American Shepherd",
      "Miniature Australian Shepherd",
      "Miniature Fox Terrier",
      "Miniature Pinscher",
      "Miniature Schnauzer",
      "Miniature Shar Pei",
      "Molossus",
      "Montenegrin Mountain Hound",
      "Moscow Watchdog",
      "Moscow Water Dog",
      "Mountain Cur",
      "Mucuchies",
      "Mudhol Hound",
      "Mudi",
      "Neapolitan Mastiff",
      "New Zealand Heading Dog",
      "Newfoundland",
      "Norfolk Spaniel",
      "Norfolk Terrier",
      "Norrbottenspets",
      "North Country Beagle",
      "Northern Inuit Dog",
      "Norwegian Buhund",
      "Norwegian Elkhound",
      "Norwegian Lundehund",
      "Norwich Terrier",
      "Old Croatian Sighthound",
      "Old Danish Pointer",
      "Old English Sheepdog",
      "Old English Terrier",
      "Old German Shepherd Dog",
      "Olde English Bulldogge",
      "Otterhound",
      "Pachon Navarro",
      "Paisley Terrier",
      "Pandikona",
      "Papillon",
      "Parson Russell Terrier",
      "Patterdale Terrier",
      "Pekingese",
      "Pembroke Welsh Corgi",
      "Perro de Presa Canario",
      "Perro de Presa Mallorquin",
      "Peruvian Hairless Dog",
      "Petit Basset Griffon Vendéen",
      "Petit Bleu de Gascogne",
      "Phalène",
      "Pharaoh Hound",
      "Phu Quoc ridgeback dog",
      "Picardy Spaniel",
      "Plott Hound",
      "Podenco Canario",
      "Pointer (dog breed)",
      "Polish Greyhound",
      "Polish Hound",
      "Polish Hunting Dog",
      "Polish Lowland Sheepdog",
      "Polish Tatra Sheepdog",
      "Pomeranian",
      "Pont-Audemer Spaniel",
      "Poodle",
      "Porcelaine",
      "Portuguese Podengo",
      "Portuguese Pointer",
      "Portuguese Water Dog",
      "Posavac Hound",
      "Pražský Krysařík",
      "Pudelpointer",
      "Pug",
      "Puli",
      "Pumi",
      "Pungsan Dog",
      "Pyrenean Mastiff",
      "Pyrenean Shepherd",
      "Rafeiro do Alentejo",
      "Rajapalayam",
      "Rampur Greyhound",
      "Rastreador Brasileiro",
      "Rat Terrier",
      "Ratonero Bodeguero Andaluz",
      "Redbone Coonhound",
      "Rhodesian Ridgeback",
      "Rottweiler",
      "Rough Collie",
      "Russell Terrier",
      "Russian Spaniel",
      "Russian tracker",
      "Russo-European Laika",
      "Sabueso Español",
      "Saint-Usuge Spaniel",
      "Sakhalin Husky",
      "Saluki",
      "Samoyed",
      "Sapsali",
      "Schapendoes",
      "Schillerstövare",
      "Schipperke",
      "Schweizer Laufhund",
      "Schweizerischer Niederlaufhund",
      "Scotch Collie",
      "Scottish Deerhound",
      "Scottish Terrier",
      "Sealyham Terrier",
      "Segugio Italiano",
      "Seppala Siberian Sleddog",
      "Serbian Hound",
      "Serbian Tricolour Hound",
      "Shar Pei",
      "Shetland Sheepdog",
      "Shiba Inu",
      "Shih Tzu",
      "Shikoku",
      "Shiloh Shepherd Dog",
      "Siberian Husky",
      "Silken Windhound",
      "Sinhala Hound",
      "Skye Terrier",
      "Sloughi",
      "Slovak Cuvac",
      "Slovakian Rough-haired Pointer",
      "Small Greek Domestic Dog",
      "Small Münsterländer",
      "Smooth Collie",
      "South Russian Ovcharka",
      "Southern Hound",
      "Spanish Mastiff",
      "Spanish Water Dog",
      "Spinone Italiano",
      "Sporting Lucas Terrier",
      "St. Bernard",
      "St. John's water dog",
      "Stabyhoun",
      "Staffordshire Bull Terrier",
      "Standard Schnauzer",
      "Stephens Cur",
      "Styrian Coarse-haired Hound",
      "Sussex Spaniel",
      "Swedish Lapphund",
      "Swedish Vallhund",
      "Tahltan Bear Dog",
      "Taigan",
      "Talbot",
      "Tamaskan Dog",
      "Teddy Roosevelt Terrier",
      "Telomian",
      "Tenterfield Terrier",
      "Thai Bangkaew Dog",
      "Thai Ridgeback",
      "Tibetan Mastiff",
      "Tibetan Spaniel",
      "Tibetan Terrier",
      "Tornjak",
      "Tosa",
      "Toy Bulldog",
      "Toy Fox Terrier",
      "Toy Manchester Terrier",
      "Toy Trawler Spaniel",
      "Transylvanian Hound",
      "Treeing Cur",
      "Treeing Walker Coonhound",
      "Trigg Hound",
      "Tweed Water Spaniel",
      "Tyrolean Hound",
      "Vizsla",
      "Volpino Italiano",
      "Weimaraner",
      "Welsh Sheepdog",
      "Welsh Springer Spaniel",
      "Welsh Terrier",
      "West Highland White Terrier",
      "West Siberian Laika",
      "Westphalian Dachsbracke",
      "Wetterhoun",
      "Whippet",
      "White Shepherd",
      "Wire Fox Terrier",
      "Wirehaired Pointing Griffon",
      "Wirehaired Vizsla",
      "Yorkshire Terrier",
      "Šarplaninac"
    ],
   "donkeys":[
      "Abkhazskaya",
      "Abyssinian Donkey",
      "Algerian",
      "American Mammoth Jack",
      "Amiatina",
      "Anatolian",
      "Andalusian Donkey",
      "Âne Africain",
      "Âne du Gourma",
      "Âne du Miankala",
      "Âne du plateau Dogon",
      "Âne du Sahel",
      "Âne du Yatenga",
      "Âne locale",
      "Âne wallon",
      "Ânes",
      "Anger",
      "Armyanskaya",
      "Asin",
      "Asinara Donkey",
      "Asino Argentato di Sologno",
      "Asino Baio Lucano",
      "Asino dell'Irpinia",
      "Asino di Sant'Alberto",
      "Asino Emiliano",
      "Asino Pugliese",
      "Asino Sardo Grigio Crociato",
      "Asnal Criolin'",
      "Asno",
      "Asno Americana",
      "Asno Balear",
      "Asno Criollo",
      "Asno de las Encartaciones",
      "Australian Donkey",
      "Austrian-Hungarian white Donkey",
      "Azerbaidzhanskaya",
      "Balkan Donkey",
      "Benderi",
      "Berry Black",
      "Berry Grey",
      "Biyang",
      "Black",
      "Bourbonnais Donkey",
      "Bourik",
      "Brasil",
      "Bulgarian Donkey",
      "Bulgaro",
      "Burro",
      "Burro Criollo",
      "Burro Kentucky",
      "Caninde",
      "Cardao",
      "Cariovilli",
      "Castel Morrone Donkey",
      "Catalan Donkey",
      "Chigetai",
      "China North",
      "Comune",
      "Corsican Donkey",
      "Cotentin Donkey",
      "Creole",
      "Criollo",
      "Cyprus Donkey",
      "Dagestanskaya",
      "Damascus",
      "Dezhou",
      "Dongolawl",
      "Dwarf Donkey of Graciosa",
      "Egypt Baladi",
      "Egyptian",
      "English Donkey",
      "Etbai",
      "Ezel",
      "Georgian Ass",
      "Green",
      "Grey",
      "Grigio Siciliano",
      "Guangling",
      "Guanzhong",
      "Hamadan",
      "Hassawi",
      "Huaibei",
      "Indian",
      "Iranian",
      "Irish Donkey",
      "Istarski Magarac",
      "Italian",
      "Jack Norteamericano",
      "Jiami",
      "Jinnan",
      "Jirnrna",
      "Kakhetinskaya",
      "Kara-Kalpakskaya",
      "Karakaçan",
      "Kashan",
      "Kassala",
      "Kazakhskaya",
      "Kirgizskaya",
      "Kulun",
      "Liangzhou",
      "Libyan",
      "Linxian",
      "Magyar Parlagi Szamár",
      "Majorera Donkey",
      "Maltese Donkey",
      "Mannar",
      "Martina Franca Donkey",
      "Maryisltaya",
      "Masai",
      "Masri",
      "Merzifon",
      "Meskhet-Dzhavakhetskaya",
      "Miniature Donkey",
      "Miranda Donkey",
      "Moldavian Local",
      "Moroccan",
      "Mula",
      "Muscat",
      "National Genatic",
      "Native of North Africa",
      "Nordestina",
      "Norman Donkey",
      "Ogaden",
      "Pantesco",
      "Paulista",
      "Pega",
      "Peruano",
      "Poitevin",
      "Poitou Donkey",
      "Ponui Donkey",
      "Primorsko Dinarski Magarac",
      "Provence Donkey",
      "Puttalam Buruwa",
      "Pyrenean Donkey",
      "Qinghai",
      "Qinqyang",
      "Qirmani",
      "Qubressy",
      "Ragusano Donkey",
      "Riffawi",
      "Romagnolo Donkey",
      "Romanian Donkey",
      "Saidi",
      "Sardinian Donkey",
      "Sennar",
      "Shanbei",
      "Sibbianl",
      "Sjeverno Jadranski Magarac",
      "Somali",
      "South-West",
      "Sperki",
      "Spotted",
      "Standard",
      "Subei",
      "Sudanese Pack",
      "Syrian",
      "Tadzhikskaya",
      "Taihang",
      "Thuringian Forest Donkey",
      "Tibetan",
      "Toposa",
      "Tswana",
      "Tunisian",
      "Turkmenskaya",
      "Uzbekskaya",
      "Viterbese",
      "Xinjiang",
      "Yangyuan",
      "Yunnan",
      "Zamorano-Leonés"
   ],
   "horses":[
      "American Albino",
      "Abaco Barb",
      "Abtenauer",
      "Abyssinian",
      "Aegidienberger",
      "Akhal-Teke",
      "Albanian Horse",
      "Altai Horse",
      "Altèr Real",
      "American Cream Draft",
      "American Indian Horse",
      "American Paint Horse",
      "American Quarter Horse",
      "American Saddlebred",
      "American Warmblood",
      "Andalusian Horse",
      "Andravida Horse",
      "Anglo-Arabian",
      "Anglo-Arabo-Sardo",
      "Anglo-Kabarda",
      "Appaloosa",
      "AraAppaloosa",
      "Arabian Horse",
      "Ardennes Horse",
      "Arenberg-Nordkirchen",
      "Argentine Criollo",
      "Asian wild Horse",
      "Assateague Horse",
      "Asturcón",
      "Augeron",
      "Australian Brumby",
      "Australian Draught Horse",
      "Australian Stock Horse",
      "Austrian Warmblood",
      "Auvergne Horse",
      "Auxois",
      "Azerbaijan Horse",
      "Azteca Horse",
      "Baise Horse",
      "Bale",
      "Balearic Horse",
      "Balikun Horse",
      "Baluchi Horse",
      "Banker Horse",
      "Barb Horse",
      "Bardigiano",
      "Bashkir Curly",
      "Basque Mountain Horse",
      "Bavarian Warmblood",
      "Belgian Half-blood",
      "Belgian Horse",
      "Belgian Warmblood ",
      "Bhutia Horse",
      "Black Forest Horse",
      "Blazer Horse",
      "Boerperd",
      "Borana",
      "Boulonnais Horse",
      "Brabant",
      "Brandenburger",
      "Brazilian Sport Horse",
      "Breton Horse",
      "Brumby",
      "Budyonny Horse",
      "Burguete Horse",
      "Burmese Horse",
      "Byelorussian Harness Horse",
      "Calabrese Horse",
      "Camargue Horse",
      "Camarillo White Horse",
      "Campeiro",
      "Campolina",
      "Canadian Horse",
      "Canadian Pacer",
      "Carolina Marsh Tacky",
      "Carthusian Horse",
      "Caspian Horse",
      "Castilian Horse",
      "Castillonnais",
      "Catria Horse",
      "Cavallo Romano della Maremma Laziale",
      "Cerbat Mustang",
      "Chickasaw Horse",
      "Chilean Corralero",
      "Choctaw Horse",
      "Cleveland Bay",
      "Clydesdale Horse",
      "Cob",
      "Coldblood Trotter",
      "Colonial Spanish Horse",
      "Colorado Ranger",
      "Comtois Horse",
      "Corsican Horse",
      "Costa Rican Saddle Horse",
      "Cretan Horse",
      "Criollo Horse",
      "Croatian Coldblood",
      "Cuban Criollo",
      "Cumberland Island Horse",
      "Curly Horse",
      "Czech Warmblood",
      "Daliboz",
      "Danish Warmblood",
      "Danube Delta Horse",
      "Dole Gudbrandsdal",
      "Don",
      "Dongola Horse",
      "Draft Trotter",
      "Dutch Harness Horse",
      "Dutch Heavy Draft",
      "Dutch Warmblood",
      "Dzungarian Horse",
      "East Bulgarian",
      "East Friesian Horse",
      "Estonian Draft",
      "Estonian Horse",
      "Falabella",
      "Faroese",
      "Finnhorse",
      "Fjord Horse",
      "Fleuve",
      "Florida Cracker Horse",
      "Foutanké",
      "Frederiksborg Horse",
      "Freiberger",
      "French Trotter",
      "Friesian Cross",
      "Friesian Horse",
      "Friesian Sporthorse",
      "Furioso-North Star",
      "Galiceño",
      "Galician Pony",
      "Gelderland Horse",
      "Georgian Grande Horse",
      "German Warmblood",
      "Giara Horse",
      "Gidran",
      "Groningen Horse",
      "Gypsy Horse",
      "Hackney Horse",
      "Haflinger",
      "Hanoverian Horse",
      "Heck Horse",
      "Heihe Horse",
      "Henson Horse",
      "Hequ Horse",
      "Hirzai",
      "Hispano-Bretón",
      "Holsteiner Horse",
      "Horro",
      "Hungarian Warmblood",
      "Icelandic Horse",
      "Iomud",
      "Irish Draught",
      "Irish Sport Horse sometimes called Irish Hunter",
      "Italian Heavy Draft",
      "Italian Trotter",
      "Jaca Navarra",
      "Jeju Horse",
      "Jutland Horse",
      "Kabarda Horse",
      "Kafa",
      "Kaimanawa Horses",
      "Kalmyk Horse",
      "Karabair",
      "Karabakh Horse",
      "Karachai Horse",
      "Karossier",
      "Kathiawari",
      "Kazakh Horse",
      "Kentucky Mountain Saddle Horse",
      "Kiger Mustang",
      "Kinsky Horse",
      "Kisber Felver",
      "Kiso Horse",
      "Kladruber",
      "Knabstrupper",
      "Konik",
      "Kundudo",
      "Kustanair",
      "Kyrgyz Horse",
      "Latvian Horse",
      "Lipizzan",
      "Lithuanian Heavy Draught",
      "Lokai",
      "Losino Horse",
      "Lusitano",
      "Lyngshest",
      "M'Bayar",
      "M'Par",
      "Mallorquín",
      "Malopolski",
      "Mangalarga",
      "Mangalarga Marchador",
      "Maremmano",
      "Marismeño Horse",
      "Marsh Tacky",
      "Marwari Horse",
      "Mecklenburger",
      "Međimurje Horse",
      "Menorquín",
      "Mérens Horse",
      "Messara Horse",
      "Metis Trotter",
      "Mezőhegyesi Sport Horse",
      "Miniature Horse",
      "Misaki Horse",
      "Missouri Fox Trotter",
      "Monchina",
      "Mongolian Horse",
      "Mongolian Wild Horse",
      "Monterufolino",
      "Morab",
      "Morgan Horse",
      "Mountain Pleasure Horse",
      "Moyle Horse",
      "Murakoz Horse",
      "Murgese",
      "Mustang Horse",
      "Namib Desert Horse",
      "Nangchen Horse",
      "National Show Horse",
      "Nez Perce Horse",
      "Nivernais Horse",
      "Nokota Horse",
      "Noma",
      "Nonius Horse",
      "Nooitgedachter",
      "Nordlandshest",
      "Noriker Horse",
      "Norman Cob",
      "North American Single-Footer Horse",
      "North Swedish Horse",
      "Norwegian Coldblood Trotter",
      "Norwegian Fjord",
      "Novokirghiz",
      "Oberlander Horse",
      "Ogaden",
      "Oldenburg Horse",
      "Orlov trotter",
      "Ostfriesen",
      "Paint",
      "Pampa Horse",
      "Paso Fino",
      "Pentro Horse",
      "Percheron",
      "Persano Horse",
      "Peruvian Paso",
      "Pintabian",
      "Pleven Horse",
      "Poitevin Horse",
      "Posavac Horse",
      "Pottok",
      "Pryor Mountain Mustang",
      "Przewalski's Horse",
      "Pura Raza Española",
      "Purosangue Orientale",
      "Qatgani",
      "Quarab",
      "Quarter Horse",
      "Racking Horse",
      "Retuerta Horse",
      "Rhenish German Coldblood",
      "Rhinelander Horse",
      "Riwoche Horse",
      "Rocky Mountain Horse",
      "Romanian Sporthorse",
      "Rottaler",
      "Russian Don",
      "Russian Heavy Draft",
      "Russian Trotter",
      "Saddlebred",
      "Salerno Horse",
      "Samolaco Horse",
      "San Fratello Horse",
      "Sarcidano Horse",
      "Sardinian Anglo-Arab",
      "Schleswig Coldblood",
      "Schwarzwälder Kaltblut",
      "Selale",
      "Sella Italiano",
      "Selle Français",
      "Shagya Arabian",
      "Shan Horse",
      "Shire Horse",
      "Siciliano Indigeno",
      "Silesian Horse",
      "Sokolsky Horse",
      "Sorraia",
      "South German Coldblood",
      "Soviet Heavy Draft",
      "Spanish Anglo-Arab",
      "Spanish Barb",
      "Spanish Jennet Horse",
      "Spanish Mustang",
      "Spanish Tarpan",
      "Spanish-Norman Horse",
      "Spiti Horse",
      "Spotted Saddle Horse",
      "Standardbred Horse",
      "Suffolk Punch",
      "Swedish Ardennes",
      "Swedish coldblood trotter",
      "Swedish Warmblood",
      "Swiss Warmblood",
      "Taishū Horse",
      "Takhi",
      "Tawleed",
      "Tchernomor",
      "Tennessee Walking Horse",
      "Tersk Horse",
      "Thoroughbred",
      "Tiger Horse",
      "Tinker Horse",
      "Tolfetano",
      "Tori Horse",
      "Trait Du Nord",
      "Trakehner",
      "Tsushima",
      "Tuigpaard",
      "Ukrainian Riding Horse",
      "Unmol Horse",
      "Uzunyayla",
      "Ventasso Horse",
      "Virginia Highlander",
      "Vlaamperd",
      "Vladimir Heavy Draft",
      "Vyatka",
      "Waler",
      "Waler Horse",
      "Walkaloosa",
      "Warlander",
      "Warmblood",
      "Welsh Cob",
      "Westphalian Horse",
      "Wielkopolski",
      "Württemberger",
      "Xilingol Horse",
      "Yakutian Horse",
      "Yili Horse",
      "Yonaguni Horse",
      "Zaniskari",
      "Žemaitukas",
      "Zhemaichu",
      "Zweibrücker"
   ],
   "ponies":[
      "American Shetland",
      "American Walking Pony",
      "Anadolu Pony",
      "Ariegeois Pony",
      "Assateague Pony",
      "Asturian Pony",
      "Australian Pony",
      "Australian Riding Pony",
      "Bali Pony",
      "Bashkir Pony",
      "Basque Pony",
      "Basuto Pony",
      "Batak Pony",
      "Bhutia Pony",
      "Bosnian Pony",
      "British Riding Pony",
      "British Spotted Pony",
      "Burmese Pony",
      "Canadian Rustic Pony",
      "Carpathian Pony",
      "Caspian Pony",
      "Chincoteague Pony",
      "Chinese Guoxia",
      "Coffin Bay Pony",
      "Connemara Pony",
      "Czechoslovakian Small Riding Pony",
      "Dales Pony",
      "Danish Sport Pony",
      "Dartmoor Pony",
      "Deli Pony",
      "Deutsches Reitpony",
      "Dülmen Pony",
      "Eriskay Pony",
      "Esperia Pony",
      "Exmoor Pony",
      "Falabella",
      "Faroe Pony",
      "Fell Pony",
      "Flores Pony",
      "French Saddle Pony",
      "Galician Pony",
      "Garrano",
      "Gayoe",
      "German Classic Pony",
      "German Riding Pony",
      "Gotland Pony",
      "Guangxi",
      "Guizhou Pony",
      "Gǔo-xìa Pony",
      "Hackney Pony",
      "Highland Pony",
      "Hokkaido Pony",
      "Hucul Pony",
      "Hunter Pony",
      "Icelandic Pony",
      "Indian Country Bred",
      "Java Pony",
      "Kerry bog Pony",
      "Landais Pony",
      "Lijiang Pony",
      "Linxian",
      "Lundy Pony",
      "Magyar Parlagi Szamár",
      "Majorera Donkey",
      "Maltese Donkey",
      "Manipuri Pony",
      "Mannar",
      "Martina Franca Donkey",
      "Maryisltaya",
      "Masai",
      "Masri",
      "Merens Pony",
      "Merzifon",
      "Meskhet-Dzhavakhetskaya",
      "Miniature Donkey",
      "Miniature Horse",
      "Miranda Donkey",
      "Miyako Pony",
      "Moldavian Local",
      "Moroccan",
      "Mula",
      "Muscat",
      "Narym Pony",
      "National Genatic",
      "Native of North Africa",
      "New Forest Pony",
      "Newfoundland Pony",
      "Noma Pony",
      "Nordestina",
      "Norman Donkey",
      "Northlands Pony",
      "Ob Pony",
      "Ogaden",
      "Pantesco",
      "Paulista",
      "Pega",
      "Peneia Pony",
      "Peruano",
      "Petiso Argentino",
      "Pindos Pony",
      "Poitevin",
      "Poitou Donkey",
      "Poney Mousseye",
      "Ponui Donkey",
      "Pony of the Americas",
      "Pottok",
      "Primorsko Dinarski Magarac",
      "Provence Donkey",
      "Puttalam Buruwa",
      "Pyrenean Donkey",
      "Qinghai",
      "Qinqyang",
      "Qirmani",
      "Quarter Pony",
      "Qubressy",
      "Ragusano Donkey",
      "Riding Pony",
      "Riffawi",
      "Romagnolo Donkey",
      "Romanian Donkey",
      "Sable Island Pony",
      "Saidi",
      "Sandalwood Pony",
      "Sardinian Donkey",
      "Sardinian Pony",
      "Sennar",
      "Shanbei",
      "Shetland Pony",
      "Sibbianl",
      "Sjeverno Jadranski Magarac",
      "Skogsruss",
      "Skyros Pony",
      "Somali",
      "South-West",
      "Sperki",
      "Spiti Pony",
      "Spotted",
      "Standard",
      "Subei",
      "Sudanese Pack",
      "Sumba and Sumbawa Pony",
      "Syrian",
      "Tadzhikskaya",
      "Taihang",
      "Thuringian Forest Donkey",
      "Tibetan",
      "Tibetan Pony",
      "Timor Pony",
      "Tokara Pony",
      "Toposa",
      "Tswana",
      "Tunisian",
      "Turkmenskaya",
      "Uzbekskaya",
      "Virginia Highlander",
      "Viterbese",
      "Vyatka Horse",
      "Welara",
      "Welsh Mountain Pony",
      "Welsh Pony",
      "Weser-Ems Pony",
      "Western Sudan Pony",
      "Xinjiang",
      "Yakut Pony",
      "Yangyuan",
      "Yonaguni",
      "Yunnan",
      "Zamorano-Leonés",
      "Zaniskari",
      "Žemaitukas",
      "Zhumd"
   ],
     "conditions": [
    "Mostly Cloudy",
    "Mostly Cloudy with Haze",
    "Mostly Cloudy and Breezy",
    "Fair",
    "Clear",
    "Fair with Haze",
    "Clear with Haze",
    "Fair and Breezy",
    "Clear and Breezy",
    "A Few Clouds",
    "A Few Clouds with Haze",
    "A Few Clouds and Breezy",
    "Partly Cloudy",
    "Partly Cloudy with Haze",
    "Partly Cloudy and Breezy",
    "Overcast",
    "Overcast with Haze",
    "Overcast and Breezy",
    "Fog/Mist",
    "Fog",
    "Freezing Fog",
    "Shallow Fog",
    "Partial Fog",
    "Patches of Fog",
    "Fog in Vicinity",
    "Freezing Fog in Vicinity",
    "Shallow Fog in Vicinity",
    "Partial Fog in Vicinity",
    "Patches of Fog in Vicinity",
    "Light Freezing Fog",
    "Heavy Freezing Fog",
    "Smoke",
    "Freezing Rain",
    "Freezing Drizzle",
    "Light Freezing Rain",
    "Light Freezing Drizzle",
    "Heavy Freezing Rain",
    "Heavy Freezing Drizzle",
    "Freezing Rain in Vicinity",
    "Freezing Drizzle in Vicinity",
    "Ice Pellets",
    "Light Ice Pellets",
    "Heavy Ice Pellets",
    "Ice Pellets in Vicinity",
    "Showers Ice Pellets",
    "Thunderstorm Ice Pellets",
    "Ice Crystals",
    "Hail",
    "Small Hail/Snow Pellets",
    "Light Small Hail/Snow Pellets",
    "Heavy small Hail/Snow Pellets",
    "Showers Hail",
    "Hail Showers",
    "Freezing Rain Snow",
    "Light Freezing Rain Snow",
    "Heavy Freezing Rain Snow",
    "Freezing Drizzle Snow",
    "Light Freezing Drizzle Snow",
    "Heavy Freezing Drizzle Snow",
    "Snow Freezing Rain",
    "Light Snow Freezing Rain",
    "Heavy Snow Freezing Rain",
    "Snow Freezing Drizzle",
    "Light Snow Freezing Drizzle",
    "Heavy Snow Freezing Drizzle",
    "Rain Ice Pellets",
    "Light Rain Ice Pellets",
    "Heavy Rain Ice Pellets",
    "Drizzle Ice Pellets",
    "Light Drizzle Ice Pellets",
    "Heavy Drizzle Ice Pellets",
    "Ice Pellets Rain",
    "Light Ice Pellets Rain",
    "Heavy Ice Pellets Rain",
    "Ice Pellets Drizzle",
    "Light Ice Pellets Drizzle",
    "Heavy Ice Pellets Drizzle",
    "Rain Snow",
    "Light Rain Snow",
    "Heavy Rain Snow",
    "Snow Rain",
    "Light Snow Rain",
    "Heavy Snow Rain",
    "Drizzle Snow",
    "Light Drizzle Snow",
    "Snow Drizzle",
    "Light Snow Drizzle",
    "Heavy Drizzle Snow",
    "Rain Showers",
    "Light Rain Showers",
    "Light Rain and Breezy",
    "Heavy Rain Showers",
    "Rain Showers in Vicinity",
    "Light Showers Rain",
    "Heavy Showers Rain",
    "Showers Rain",
    "Showers Rain in Vicinity",
    "Rain Showers Fog/Mist",
    "Light Rain Showers Fog/Mist",
    "Heavy Rain Showers Fog/Mist",
    "Rain Showers in Vicinity Fog/Mist",
    "Light Showers Rain Fog/Mist",
    "Heavy Showers Rain Fog/Mist",
    "Showers Rain Fog/Mist",
    "Showers Rain in Vicinity Fog/Mist",
    "Thunderstorm",
    "Thunderstorm Rain",
    "Light Thunderstorm Rain",
    "Heavy Thunderstorm Rain",
    "Light Thunderstorm Rain Haze",
    "Heavy Thunderstorm Rain Haze",
    "Thunderstorm Fog",
    "Light Thunderstorm Rain Fog",
    "Heavy Thunderstorm Rain Fog",
    "Thunderstorm Light Rain",
    "Thunderstorm Heavy Rain",
    "Thunderstorm Rain Fog/Mist",
    "Thunderstorm Light Rain Fog/Mist",
    "Thunderstorm Heavy Rain Fog/Mist",
    "Thunderstorm in Vicinity Fog/Mist",
    "Thunderstorm Showers in Vicinity",
    "Thunderstorm in Vicinity Haze",
    "Thunderstorm Haze in Vicinity",
    "Thunderstorm Light Rain Haze",
    "Thunderstorm Heavy Rain Haze",
    "Thunderstorm Light Rain Fog",
    "Thunderstorm Heavy Rain Fog",
    "Thunderstorm Hail",
    "Light Thunderstorm Rain Hail",
    "Heavy Thunderstorm Rain Hail",
    "Light Thunderstorm Rain Hail Fog/Mist",
    "Heavy Thunderstorm Rain Hail Fog/Hail",
    "Thunderstorm Showers in Vicinity Hail",
    "Light Thunderstorm Rain Hail Haze",
    "Heavy Thunderstorm Rain Hail Haze",
    "Thunderstorm Hail Fog",
    "Light Thunderstorm Rain Hail Fog",
    "Heavy Thunderstorm Rain Hail Fog",
    "Thunderstorm Light Rain Hail",
    "Thunderstorm Heavy Rain Hail",
    "Thunderstorm Rain Hail Fog/Mist",
    "Thunderstorm Light Rain Hail Fog/Mist",
    "Thunderstorm Heavy Rain Hail Fog/Mist",
    "Thunderstorm in Vicinity Hail",
    "Thunderstorm in Vicinity Hail Haze",
    "Thunderstorm Haze in Vicinity Hail",
    "Thunderstorm Light Rain Hail Haze",
    "Thunderstorm Heavy Rain Hail Haze",
    "Thunderstorm Light Rain Hail Fog",
    "Thunderstorm Heavy Rain Hail Fog",
    "Thunderstorm Small Hail/Snow Pellets",
    "Thunderstorm Rain Small Hail/Snow Pellets",
    "Light Thunderstorm Rain Small Hail/Snow Pellets",
    "Heavy Thunderstorm Rain Small Hail/Snow Pellets",
    "Snow",
    "Light Snow",
    "Heavy Snow",
    "Snow Showers",
    "Light Snow Showers",
    "Heavy Snow Showers",
    "Showers Snow",
    "Light Showers Snow",
    "Heavy Showers Snow",
    "Snow Fog/Mist",
    "Light Snow Fog/Mist",
    "Heavy Snow Fog/Mist",
    "Snow Showers Fog/Mist",
    "Light Snow Showers Fog/Mist",
    "Heavy Snow Showers Fog/Mist",
    "Showers Snow Fog/Mist",
    "Light Showers Snow Fog/Mist",
    "Heavy Showers Snow Fog/Mist",
    "Snow Fog",
    "Light Snow Fog",
    "Heavy Snow Fog",
    "Snow Showers Fog",
    "Light Snow Showers Fog",
    "Heavy Snow Showers Fog",
    "Showers Snow Fog",
    "Light Showers Snow Fog",
    "Heavy Showers Snow Fog",
    "Showers in Vicinity Snow",
    "Snow Showers in Vicinity",
    "Snow Showers in Vicinity Fog/Mist",
    "Snow Showers in Vicinity Fog",
    "Low Drifting Snow",
    "Blowing Snow",
    "Snow Low Drifting Snow",
    "Snow Blowing Snow",
    "Light Snow Low Drifting Snow",
    "Light Snow Blowing Snow",
    "Light Snow Blowing Snow Fog/Mist",
    "Heavy Snow Low Drifting Snow",
    "Heavy Snow Blowing Snow",
    "Thunderstorm Snow",
    "Light Thunderstorm Snow",
    "Heavy Thunderstorm Snow",
    "Snow Grains",
    "Light Snow Grains",
    "Heavy Snow Grains",
    "Heavy Blowing Snow",
    "Blowing Snow in Vicinity",
    "Windy",
    "Breezy",
    "Fair and Windy",
    "A Few Clouds and Windy",
    "Partly Cloudy and Windy",
    "Mostly Cloudy and Windy",
    "Overcast and Windy",
    "Showers in Vicinity",
    "Showers in Vicinity Fog/Mist",
    "Showers in Vicinity Fog",
    "Showers in Vicinity Haze",
    "Freezing Rain Rain",
    "Light Freezing Rain Rain",
    "Heavy Freezing Rain Rain",
    "Rain Freezing Rain",
    "Light Rain Freezing Rain",
    "Heavy Rain Freezing Rain",
    "Freezing Drizzle Rain",
    "Light Freezing Drizzle Rain",
    "Heavy Freezing Drizzle Rain",
    "Rain Freezing Drizzle",
    "Light Rain Freezing Drizzle",
    "Heavy Rain Freezing Drizzle",
    "Thunderstorm in Vicinity",
    "Thunderstorm in Vicinity Fog",
    "Light Rain",
    "Drizzle",
    "Light Drizzle",
    "Heavy Drizzle",
    "Light Rain Fog/Mist",
    "Drizzle Fog/Mist",
    "Light Drizzle Fog/Mist",
    "Heavy Drizzle Fog/Mist",
    "Light Rain Fog",
    "Drizzle Fog",
    "Light Drizzle Fog",
    "Heavy Drizzle Fog",
    "Rain",
    "Heavy Rain",
    "Rain Fog/Mist",
    "Heavy Rain Fog/Mist",
    "Rain Fog",
    "Heavy Rain Fog",
    "Funnel Cloud",
    "Funnel Cloud in Vicinity",
    "Tornado/Water Spout",
    "Dust",
    "Low Drifting Dust",
    "Blowing Dust",
    "Sand",
    "Blowing Sand",
    "Low Drifting Sand",
    "Dust/Sand Whirls",
    "Dust/Sand Whirls in Vicinity",
    "Dust Storm",
    "Heavy Dust Storm",
    "Dust Storm in Vicinity",
    "Sand Storm",
    "Heavy Sand Storm",
    "Sand Storm in Vicinity",
    "Haze"
  ],
  "space_words": [
    "Space",
    "Earth",
    "Solar System",
    "Jupiter",
    "Mars",
    "quarter moon",
    "Neptune",
    "moon",
    "gibbous moon",
    "Mercury",
    "Pluto",
    "half moon",
    "Saturn",
    "Venus",
    "crescent moon",
    "Uranus",
    "planet",
    "axial tilt",
    "waning",
    "waxing",
    "asteroid belt",
    "asteroid",
    "black hole",
    "big bang theory",
    "astronaut",
    "comet",
    "binary star",
    "astronomer",
    "astronomy",
    "elliptical orbit",
    "density",
    "constellation",
    "deep space",
    "cosmonaut",
    "cosmos",
    "dwarf planet",
    "crater",
    "day",
    "dwarf star",
    "dust",
    "equinox",
    "inner planets",
    "eclipse",
    "ecliptic",
    "inferior planets",
    "galaxy",
    "lunar",
    "falling star",
    "meteorite",
    "meteor",
    "meteor shower",
    "meteoroid",
    "lens",
    "gravity",
    "full moon",
    "inertia",
    "Milky Way",
    "mass",
    "magnitude",
    "outer planets",
    "nebula",
    "orbit",
    "shooting star",
    "rocket",
    "solar",
    "space exploration",
    "solstice",
    "star",
    "total eclipse",
    "umbra",
    "space",
    "vernal equinox",
    "sky",
    "satellite",
    "solar system",
    "new moon",
    "penumbra",
    "solar wind",
    "light-year",
    "rings",
    "partial eclipse",
    "observatory",
    "phase",
    "orbital inclination",
    "universe",
    "zodiac",
    "space station",
    "sun",
    "starlight and telescope"
  ],
  "authors": [
    "Arnaud",
    "Audin",
    "Beaudouin",
    "Becker",
    "Bénabou",
    "Bens",
    "Berge",
    "Berti",
    "Blavier",
    "Braffort",
    "Calvino",
    "Caradec",
    "Cerquiglini",
    "Chambers",
    "Chapman",
    "Duchamp",
    "Duchateau",
    "Etienne",
    "Forte",
    "Fournel",
    "Garréta",
    "Grangaud",
    "Jouet",
    "Lécroart",
    "Lescure",
    "Lionnais",
    "Mathews",
    "Mélois",
    "members",
    "Métail",
    "Monk",
    "Pastior",
    "Peillet",
    "Perec",
    "Queneau",
    "Queval",
    "Rosenstiehl",
    "Roubaud",
    "Salon",
    "Sánchez",
    "Schmidt",
    "Tellier"
  ]
}
