repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
        exclude: ^css/minireset\.min\.css$|^js/lib/tracery\.js$
